In [9]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 
%matplotlib inline

In [10]:
df = pd.read_csv('train.csv')
df.shape

(594194, 21)

In [11]:
df.sample(5)

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
156544,156544,Male,0,Yes,No,9,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,74.70,633.70,No
513313,513313,Female,0,No,No,2,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Electronic check,86.45,157.35,No
325071,325071,Female,0,Yes,No,62,Yes,Yes,DSL,Yes,...,No,Yes,No,No,One year,Yes,Bank transfer (automatic),63.75,4798.30,No
11214,11214,Male,0,Yes,No,61,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,One year,Yes,Electronic check,111.50,6841.05,No
329765,329765,Female,0,Yes,No,9,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),69.55,633.65,Yes

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594194 entries, 0 to 594193
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                594194 non-null  int64
 1   gender            594194 non-null  object
 2   SeniorCitizen     594194 non-null  int64
 3   Partner           594194 non-null  object
 4   Dependents        594194 non-null  object
 5   tenure            594194 non-null  int64
 6   PhoneService      594194 non-null  object
 7   MultipleLines     594194 non-null  object
 8   InternetService   594194 non-null  object
 9   OnlineSecurity    594194 non-null  object
 10  OnlineBackup      594194 non-null  object
 11  DeviceProtection  594194 non-null  object
 12  TechSupport       594194 non-null  object
 13  StreamingTV       594194 non-null  object
 14  StreamingMovies   594194 non-null  object
 15  Contract          594194 non-null  object
 16  PaperlessBilling  594194 non-null  object
 17  PaymentMethod     594194 non-null  object
 18  MonthlyCharges    594194 non-null  float64
 19  TotalCharges      594194 non-null  float64
 20  Churn             594194 non-null  object
dtypes: float64(2), int64(3), object(16)
memory usage: 95.2+ MB

In [13]:
df = df.iloc[:,1:]
df.shape

(594194, 20)

In [14]:
df.isnull().sum()[df.isnull().sum()>0]

Series([], dtype: int64)

In [15]:
df.describe()

       SeniorCitizen         tenure  MonthlyCharges   TotalCharges
count  594194.000000  594194.000000   594194.000000  594194.000000
mean        0.114102      36.577258       65.866223    2494.377057
std         0.317936      25.061922       31.067444    2353.916710
min         0.000000       1.000000       18.250000      18.800000
25%         0.000000      12.000000       29.900000     639.650000
50%         0.000000      35.000000       74.100000    1433.650000
75%         0.000000      62.000000       90.800000    4263.800000
max         1.000000      72.000000      118.750000    8684.800000

In [16]:
df.duplicated().sum()

np.int64(0)

In [18]:
for col in df.columns:
    print(col)
    print(df[col].unique())
    print('-' * 50)

gender
['Male' 'Female']
--------------------------------------------------
SeniorCitizen
[0 1]
--------------------------------------------------
Partner
['Yes' 'No']
--------------------------------------------------
Dependents
['Yes' 'No']
--------------------------------------------------
tenure
[29 58  1 24 72 55 13 67 33 63  3 31 27 52 68 35 66 17 59 61 12 37 64 23
  9  8 15 18 19 51  5 71 60 62 45 69 40 53 54 34  2 70 39 41  4 22 46 28
 42 48 21 43 14 10 47  7 57 36 16 26 20 50 30 11 44 25 56  6 65 38 49 32]
--------------------------------------------------
PhoneService
['Yes' 'No']
--------------------------------------------------
MultipleLines
['No' 'Yes' 'No phone service']
--------------------------------------------------
InternetService
['DSL' 'Fiber optic' 'No']
--------------------------------------------------
OnlineSecurity
['Yes' 'No' 'No internet service']
--------------------------------------------------
OnlineBackup
['No' 'Yes' 'No internet service']
--------------------------------------------------
DeviceProtection
['Yes' 'No' 'No internet service']
--------------------------------------------------
TechSupport
['Yes' 'No' 'No internet service']
--------------------------------------------------
StreamingTV
['No' 'Yes' 'No internet service']
--------------------------------------------------
StreamingMovies
['No' 'Yes' 'No internet service']
--------------------------------------------------
Contract
['One year' 'Two year' 'Month-to-month']
--------------------------------------------------
PaperlessBilling
['Yes' 'No']
--------------------------------------------------
PaymentMethod
['Mailed check' 'Credit card (automatic)' 'Electronic check'
 'Bank transfer (automatic)']
--------------------------------------------------
MonthlyCharges
[ 60.1   69.5  100.4  ...  18.45 112.05  46.15]
--------------------------------------------------
TotalCharges
[1653.85 3778.2  5841.35 ... 1478.9  1284.75 5460.7 ]
--------------------------------------------------
Churn
['No' 'Yes']
--------------------------------------------------